spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: aiservices.models.Activity
        spring.json.trusted.packages: "*"

  mongodb:
    uri: mongodb://localhost:27017/airecommendedFitness
    database: airecommendedFitness

gemini:
  api:
    url: https://api.groq.com/openai/v1/chat/completions
    key: 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

kafka:
  topic: activity-events

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true